### PR TITLE
Move SRAM docs from this repo to gf180mcu_fd_ip_sram repo

### LINKED ISSUE #11: Move the SRAM documentation into the SRAM IP repository
The documentation at https://github.com/google/gf180mcu-pdk/tree/main/docs/digital/SRAM should be in the repository found at https://github.com/google/globalfoundries-pdk-ip-gf180mcu_fd_ip_sram

### PR DESCRIPTION
**Pull request by mohanad0mohamed**
- SRAM docs moved to gf180mcu_fd_ip_sram repo
- Docs are added in pull request https://github.com/google/globalfoundries-pdk-ip-gf180mcu_fd_ip_sram/pull/5

Fixes #11

### CODE REVIEW

**Comment by mithro** [comment]
I have reworked this pull request in a branch at https://github.com/mithro/gf180mcu-pdk/tree/move_sram

**Comment by mithro** [comment]
The key differences between my version and yours;
 * Only includes changes to SRAM related files.
 * Updates the `gf180mcu_fd_ip_sram` repository submodule at the same time as removing the content.

**Comment by mithro** [comment]
I'll merge this pull request if the documentation build looks good.

**Comment by mohanad0mohamed** [comment]
@mithro I think we still need to edit the `index.rst` file to include the new SRAM directory. Also I found that `ip.rst` is removed which was calling SRAM docs.

**Comment by mohanad0mohamed** [comment]
Also in this PR, it should close #15. but already another PR is made for it here #32.

**Comment by mohanad0mohamed** [comment]
Updated `index.rst` and added `ip.rst`

**Comment by mohanad0mohamed** [comment]
I have moved `code_of_conduct.rst` and `contributing.rst` outside `docs` not to produce warnings. Also edited `README.rst` to change 180um to 180nm.

**Comment by mohanad0mohamed** [comment]
I have changed the symbolic link name from `SRAM` to `gf180mcu_fd_ip_sram` to match naming

**Review by mithro — APPROVED** [review]
This looks to have worked correctly.

**Comment by mithro** [comment]
I have updated this pull request. If readthedocs goes green, then I'll merge the pull request.

**Review by atorkmabrains — APPROVED** [review]
I approve this change for merge.

**Pull request merged**
