### PR TITLE
Moving SRAM from digital to IP

### LINKED ISSUE #15: The SRAM should probably be in the `IPs` section and not the `digital` section
Currently in the documentation, SRAM is found under the `digital` section at https://gf180mcu-pdk.readthedocs.io/en/latest/digital/SRAM/sram.html

However, in this repository the SRAM is found under https://github.com/google/gf180mcu-pdk/tree/main/macros/gf180mcu_fd_ip_sram and the repository is named `gf180mcu_fd_ip_sram`.

### PR DESCRIPTION
**Pull request by mohanad0mohamed**
Fixes #15 

- SRAM moved from digital to IP
- IO renamed from IP to IO

### CODE REVIEW

**Review by atorkmabrains — APPROVED** [review]
I approve this change per @mithro request.

**Comment by mithro** [comment]
I think this pull request will need to be reworked due to the moving of documentation out of this repository.

**Review by mithro — CHANGES_REQUESTED** [review]
Let's defer this until all the docs moving out of this repository have landed successful.

**Comment by mohanad0mohamed** [comment]
@mithro @atorkmabrains I think this pull request should be closed without merging because the latest version of this repository already moved the SRAM docs from `digital` directory to `IPs` directory.

https://github.com/google/gf180mcu-pdk/tree/main/docs/IPs/SRAM

**Pull request closed without merging**
