### PR TITLE
Enable additional PDF output for readthedocs.io

### PR DESCRIPTION
**Pull request by cbalint13**
Enable as per proposed here: https://github.com/google/gf180mcu-pdk/pull/79#issuecomment-1269144168
Following ```readthedocs```:  https://docs.readthedocs.io/en/stable/config-file/v1.html#formats

~Cristian.

### CODE REVIEW

**Comment by mithro** [comment]
I'm not sure that the config file is working as intended as I can't see the PDF linked from the build and I don't see it getting built in the logs.

I think we have previously had issues with config file v1 not working correctly? --> https://github.com/google/open-source-pdks/pull/22/files -- It seems the v1 config format is deprecated?

**Comment by cbalint13** [comment]
> I'm not sure that the config file is working as intended as I can't see the PDF linked from the build and I don't see it getting built in the logs.

* On ```skywater-pdk```  works fine (it is v2): https://skywater-pdk.readthedocs.io/_/downloads/en/main/pdf/ 
* That one has v2: https://github.com/google/skywater-pdk/blob/main/.readthedocs.yml

> I think we have previously had issues with config file v1 not working correctly? --> https://github.com/google/open-source-pdks/pull/22/files -- It seems the v1 config format is deprecated?

* Let's see now, upgraded this to v2.

**Comment by cbalint13** [comment]
> 



> > I'm not sure that the config file is working as intended as I can't see the PDF linked from the build and I don't see it getting built in the logs.
> 
> * On `skywater-pdk`  works fine (it is v2): https://skywater-pdk.readthedocs.io/_/downloads/en/main/pdf/
> * That one has v2: https://github.com/google/skywater-pdk/blob/main/.readthedocs.yml
> 
> > I think we have previously had issues with config file v1 not working correctly? --> https://github.com/google/open-source-pdks/pull/22/files -- It seems the v1 config format is deprecated?
> 
> * Let's see now, upgraded this to v2.

@mithro 

Can try merge in this state ?

* Seems that in the **state of open PR** the pdf variant is not generated (sphinx not even launch the ```-b pdf```).
* See ```skywater-pdk``` PR **before** merge: https://skywater-pdk--398.org.readthedocs.build/en/398 (only html generated)
* But **after PR was merged** the PDF just appeared:  https://skywater-pdk.readthedocs.io/_/downloads/en/main/pdf/

In addition, fixed the fetch of ```third_party/open-source-pdk``` (at a point sphinx warned of some missing references)

**Review by mithro — APPROVED** [review]

**Comment by mithro** [comment]
Let's give it a go!

**Comment by mithro** [comment]
Seems like it worked! - https://gf180mcu-pdk.readthedocs.io/_/downloads/en/latest/pdf/

**Pull request merged**
