### PR TITLE
Move IO docs to gf180mcu_fd_io repo

### LINKED ISSUE #12: Move the IO cell documentation into the IO cell repository
The documentation found in this repository at https://github.com/google/gf180mcu-pdk/tree/main/docs/IPs/IO/gf180mcu_fd_io should be in the repository https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_io

### PR DESCRIPTION
**Pull request by mohanad0mohamed**
- IO docs moved to [`gf180mcu_fd_io repo`](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_io)
- Docs are added in pull request https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_io/pull/2

Fixes #12

### CODE REVIEW

**Comment by mithro** [comment]
I have started reworking this pull request in my branch at https://github.com/mithro/gf180mcu-pdk/tree/move_io

It is still missing the submodule update.

**Comment by mithro** [comment]
You should include a link to the pull request at https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_io/pull/2 in the pull request description.

**Comment by mohanad0mohamed** [comment]
I think the `index.rst` file should be updated by removing `IPs/ips` line from it.

**Comment by mohanad0mohamed** [comment]
Updated `index.rst` not to give us warnings on missing files.

**Review by atorkmabrains — APPROVED** [review]
I approve this request per @mithro request.

**Comment by mithro** [comment]
@mohanad0mohamed - You didn't update the pull request description to point to the pull request on the `globalfoundries-pdk-libs-gf180mcu_fd_io` repository which adds the documentation there.

**Review by mithro — APPROVED** [review]
I have reworked this pull request, if this goes green I'll merge it.

**Pull request merged**
